SistemaTime/Models/Times.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SistemaTime.Models
{
    public class Times
    {
        [Display(Name ="Id")]
        public int TimesId { get; set; }


        [Required(ErrorMessage ="Informe o nome do time")]
        public string Time { get; set; }

        [Required(ErrorMessage = "Informe o estado do time")]
        public string Estado { get; set; }

        [Required(ErrorMessage = "Informe as cores do time")]
        public string Cores { get; set; }
    }
}

SistemaTime/Controllers/TimeController.cs
using SistemaTime.Models;
using SistemaTime.Repositorio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SistemaTime.Controllers
{
    public class TimeController : Controller
    {

        private TimeRepositorio _repositorio;

        public ActionResult ObterTimes()
        {
            _repositorio = new TimeRepositorio();

            ModelState.Clear();
            return View(_repositorio.ObterTimes());

        }

        [HttpGet]
        public ActionResult IncluirTime()
        {
            return View();
        }


        [HttpPost]
        public ActionResult IncluirTime(Times timeObj)
        {
            try{
                if(ModelState.IsValid)
                {
                    _repositorio = new TimeRepositorio();
                    if (_repositorio.AdicionarTime(timeObj))
                    {
                        ViewBag.Mensagem = "Time cadastrado com sucesso";
                    }
                    
                }
                return View();
            }
            catch (Exception)
            {
                return View("ObterTimes");
            }
        }


        [HttpGet]
        public ActionResult EditarTime(int id)
        {
            _repositorio = new TimeRepositorio();
            return View(_repositorio.ObterTimes().Find(t => t.TimesId==id));
        }


        [HttpPost]
        public ActionResult EditarTime(int id , Times timeObj)
        {
            try
            {
                _repositorio = new TimeRepositorio();
                _repositorio.AtualizarTime(timeObj);
                return RedirectToAction("ObterTimes");

            }
            catch (Exception)
            {
                return View("ObterTimes");
            }
        }
    
        
        public ActionResult ExcluirTime(int id)
        {
            try
            {
                _repositorio = new TimeRepositorio();
                if (_repositorio.ExcluirTime(id))
                {
                    ViewBag.Mensagem = "Time excluido com sucesso";
                }
                return RedirectToAction("ObterTimes");
            }
            catch (Exception)
            {
                return View("ObterTimes");
            }
        }
    }
}

SistemaTime/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Sistema de Times</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Sistema de Times", "ObterTimes", "Time", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year | Sistema de Times| Jéssica Rodrigues</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

SistemaTime/Views/Time/EditarTime.cshtml
@model SistemaTime.Models.Times

@{
    ViewBag.Title = "EditarTime";
}

<h2>Alterar Time</h2>

<div>
    @Html.ActionLink("Listar todos os times", "ObterTimes")
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Times</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.TimesId)

    <div class="form-group">
        @Html.LabelFor(model => model.Time, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Time, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cores, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cores, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cores, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>

    @ViewBag.Mensagem
</div>
}

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

SistemaTime/Views/Time/IncluirTime.cshtml
@model SistemaTime.Models.Times

@{
    ViewBag.Title = "IncluirTime";
}

<h2>Cadastrar time</h2>


<div>

    @Html.ActionLink("Listar todos os times", "ObterTimes")

</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Times</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Time, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Time, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cores, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cores, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cores, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Salvar" class="btn btn-default" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10" style="color:forestgreen">
            @ViewBag.Mensagem
        </div>
    </div>
    
</div>
}

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

SistemaTime/Views/Time/ObterTimes.cshtml
@model IEnumerable<SistemaTime.Models.Times>

<h2>Todos os times</h2>

<p>
    @Html.ActionLink("Adicionar novo time", "IncluirTime")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Time)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cores)
        </th>
        <th>
            Ações
        </th>
    </tr>

    @foreach (var item in Model)
    {

        @Html.HiddenFor(model => item.TimesId)

        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Time)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cores)
            </td>
            <td>
                @Html.ActionLink("Alterar", "EditarTime", new { id = item.TimesId }) |
                @Html.ActionLink("Excluir", "ExcluirTime", new { id = item.TimesId }, new { onclick = "return confirm('Tem certeza que deseja excluir??');"})
            </td>
        </tr>
    }

</table>